# Generated by Django 5.2 on 2025-05-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=50)),
                ('reason_for_return', models.TextField()),
                ('product_condition', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('return_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial_refund', 'Partial Refund'), ('full_refund', 'Full Refund'), ('no_refund', 'No Refund')], default='pending', max_length=20)),
            ],
        ),
    ]
