# Generated by Django 5.2 on 2025-05-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Return Request', 'verbose_name_plural': 'Return Requests'},
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_type',
            field=models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund'), ('none', 'No Refund')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='within_return_period',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image of the product', null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='product_condition',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=50),
        ),
    ]
